 var markers = [
 {
   "BuildingID": "60491",
   "Rank": "98",
   "LandlordID": "60491",
   "Boro": "BRONX",
   "HouseNumber": "2201",
   "LowHouseNumber": "2201",
   "HighHouseNumber": "2205",
   "StreetName": "DAVIDSON AVENUE",
   "StreetCode": "23520",
   "Zip": "10453",
   "Apartment": "",
   "Story": "All Stories",
   "num": "342",
   "a": "23",
   "b": "164",
   "c": "154",
   "i": "1",
   "dob": "17",
   "BIN": "2014205",
   "housingCourt": "0",
   "dob_hpd": "359",
   "score": "8.7551",
   "A_UNITS": "49",
   "B_UNITS": "0",
   "OWNER1": "ROMAD REALTY INC",
   "ORGANIZATION": "ROMAD REALTY INC",
   "OWNER1_LN": "SUTTON",
   "OWNER1_FN": "DAVID",
   "officer": "DAVID SUTTON",
   "org": "ROMAD REALTY INC",
   "lat": "40.8577",
   "lng": "-73.9058",
   "worstLandlord": "1"
 },
 {
   "BuildingID": "67128",
   "Rank": "99",
   "LandlordID": "67128",
   "Boro": "BRONX",
   "HouseNumber": "206",
   "LowHouseNumber": "206",
   "HighHouseNumber": "214",
   "StreetName": "EAST 198 STREET",
   "StreetCode": "27600",
   "Zip": "10458",
   "Apartment": "D5",
   "Story": "",
   "num": "128",
   "a": "26",
   "b": "82",
   "c": "20",
   "i": "0",
   "dob": "0",
   "BIN": "2017146",
   "housingCourt": "0",
   "dob_hpd": "128",
   "score": "4.30769",
   "A_UNITS": "26",
   "B_UNITS": "0",
   "OWNER1": "210 EAST 198 REALTY GROUP, LLC",
   "ORGANIZATION": "210 EAST 198 REALTY GROUP, LLC",
   "OWNER1_LN": "PETERS",
   "OWNER1_FN": "ABE",
   "officer": "ABE PETERS",
   "org": "210 EAST 198 REALTY GROUP, LLC",
   "lat": "40.8696",
   "lng": "-73.8905",
   "worstLandlord": "1"
 },
 {
   "BuildingID": "215921",
   "Rank": "99",
   "LandlordID": "67128",
   "Boro": "BROOKLYN",
   "HouseNumber": "1526",
   "LowHouseNumber": "1524",
   "HighHouseNumber": "1530",
   "StreetName": "BUSHWICK AVENUE",
   "StreetCode": "23930",
   "Zip": "11207",
   "Apartment": "2F",
   "Story": "",
   "num": "74",
   "a": "19",
   "b": "36",
   "c": "19",
   "i": "0",
   "dob": "1",
   "BIN": "3080421",
   "housingCourt": "0",
   "dob_hpd": "75",
   "score": "3.325",
   "A_UNITS": "20",
   "B_UNITS": "0",
   "OWNER1": "ABERDEEN STREET REALTY LLC",
   "ORGANIZATION": "ABERDEEN STREET REALTY LLC",
   "OWNER1_LN": "PETERS",
   "OWNER1_FN": "ABE",
   "officer": "ABE PETERS",
   "org": "ABERDEEN STREET REALTY LLC",
   "lat": "40.6822",
   "lng": "-73.906",
   "worstLandlord": "1"
 },
 {
   "BuildingID": "266026",
   "Rank": "99",
   "LandlordID": "67128",
   "Boro": "BROOKLYN",
   "HouseNumber": "472",
   "LowHouseNumber": "472",
   "HighHouseNumber": "472",
   "StreetName": "EAST 48 STREET",
   "StreetCode": "36930",
   "Zip": "11203",
   "Apartment": "",
   "Story": "",
   "num": "151",
   "a": "25",
   "b": "62",
   "c": "64",
   "i": "0",
   "dob": "0",
   "BIN": "3102767",
   "housingCourt": "0",
   "dob_hpd": "151",
   "score": "5.26667",
   "A_UNITS": "30",
   "B_UNITS": "0",
   "OWNER1": "UNITED LUBAVITCHER YESHIVOTH",
   "ORGANIZATION": "UNITED LUBAVITCHER YESHIVOTH",
   "OWNER1_LN": "PETERS",
   "OWNER1_FN": "ABE",
   "officer": "ABE PETERS",
   "org": "UNITED LUBAVITCHER YESHIVOTH",
   "lat": "40.6503",
   "lng": "-73.9322",
   "worstLandlord": "1"
 },
 {
   "BuildingID": "218219",
   "Rank": "100",
   "LandlordID": "218219",
   "Boro": "BROOKLYN",
   "HouseNumber": "951",
   "LowHouseNumber": "951",
   "HighHouseNumber": "957",
   "StreetName": "CARROLL STREET",
   "StreetCode": "24830",
   "Zip": "11225",
   "Apartment": "3-F",
   "Story": "3",
   "num": "139",
   "a": "29",
   "b": "93",
   "c": "17",
   "i": "0",
   "dob": "5",
   "BIN": "3033446",
   "housingCourt": "0",
   "dob_hpd": "144",
   "score": "3.29487",
   "A_UNITS": "39",
   "B_UNITS": "0",
   "OWNER1": "CARROLL ST ASSOCIATES LLC",
   "ORGANIZATION": "CARROLL ST ASSOCIATES LLC",
   "OWNER1_LN": "SAYEGH",
   "OWNER1_FN": "ALFRED",
   "officer": "ALFRED SAYEGH",
   "org": "CARROLL ST ASSOCIATES LLC",
   "lat": "40.6682",
   "lng": "-73.9586",
   "worstLandlord": "1"
 },
 {
   "BuildingID": "309407",
   "Rank": "100",
   "LandlordID": "218219",
   "Boro": "BROOKLYN",
   "HouseNumber": "78",
   "LowHouseNumber": "78",
   "HighHouseNumber": "78",
   "StreetName": "HAWTHORNE STREET",
   "StreetCode": "48230",
   "Zip": "11225",
   "Apartment": "4G",
   "Story": "",
   "num": "96",
   "a": "13",
   "b": "46",
   "c": "37",
   "i": "0",
   "dob": "0",
   "BIN": "3115671",
   "housingCourt": "0",
   "dob_hpd": "96",
   "score": "2.81944",
   "A_UNITS": "36",
   "B_UNITS": "0",
   "OWNER1": "BERKLEY MILLS PARTNERS LLC",
   "ORGANIZATION": "BERKLEY MILLS PARTNERS LLC",
   "OWNER1_LN": "SAYEGH",
   "OWNER1_FN": "ALFRED",
   "officer": "ALFRED SAYEGH",
   "org": "BERKLEY MILLS PARTNERS LLC",
   "lat": "40.6572",
   "lng": "-73.9577",
   "worstLandlord": "1"
 },
 {
   "BuildingID": "347778",
   "Rank": "100",
   "LandlordID": "218219",
   "Boro": "BROOKLYN",
   "HouseNumber": "726",
   "LowHouseNumber": "726",
   "HighHouseNumber": "726",
   "StreetName": "OCEAN AVENUE",
   "StreetCode": "67530",
   "Zip": "11226",
   "Apartment": "51",
   "Story": "",
   "num": "109",
   "a": "24",
   "b": "32",
   "c": "53",
   "i": "0",
   "dob": "4",
   "BIN": "3117614",
   "housingCourt": "0",
   "dob_hpd": "113",
   "score": "3.98333",
   "A_UNITS": "30",
   "B_UNITS": "0",
   "OWNER1": "BEEKMAN FIRST ASSOCIATES LLC",
   "ORGANIZATION": "BEEKMAN FIRST ASSOCIATES LLC",
   "OWNER1_LN": "SAYEGH",
   "OWNER1_FN": "ALFRED",
   "officer": "ALFRED SAYEGH",
   "org": "BEEKMAN FIRST ASSOCIATES LLC",
   "lat": "40.6451",
   "lng": "-73.9605",
   "worstLandlord": "1"
 }
    ];
	var lat = "";
	var lng = "";
	var count = "";
	var pins = "";
	for (i=0; i<markers.lenght; i++)
	{
		for (j=0; j<markers.length; j++_)
		{
		var data=markers[j];
		while (data.Rank == (i+1)){
			
		lat = + markers[j].lat +;
		lng = + markers[j].lng +;
		 pins += + lat + lng +;		 
		
		
		}
		}
		
		
	}