var markers = [
 {
   "BuildingID": "797473",
   "LandlordID": "797473",
   "Boro": "STATEN ISLAND",
   "HouseNumber": "99",
   "LowHouseNumber": "99",
   "HighHouseNumber": "99",
   "StreetName": "WRIGHT STREET",
   "StreetCode": "56450",
   "Zip": "10304",
   "FIELD10": "99 WRIGHT STREET New York, NY 10304",
   "Apartment": "",
   "Story": "All Stories",
   "num": "203",
   "a": "36",
   "b": "103",
   "c": "61",
   "i": "3",
   "dob": "0",
   "BIN": "5013684",
   "dob_hpd": "203",
   "score": "48.625",
   "A_UNITS": "4",
   "B_UNITS": "0",
   "OWNER1": "GRINBERG MANAGEMENT AND DEVELOPMENT LLC",
   "ORGANIZATION": "GRINBERG MANAGEMENT AND DEVELOPMENT LLC",
   "OWNER1_LN": "MARCIANO",
   "OWNER1_FN": "JEFFREY ",
   "officer": "JEFFREY  MARCIANO",
   "org": "GRINBERG MANAGEMENT AND DEVELOPMENT LLC",
   "lat": "40.627891",
   "lng": "-74.079124",
   "exclude": "0",
   "worstLandlord": null,
   "UNITS": "4",
   "DOF": "1"
 },
 {
   "BuildingID": "790359",
   "LandlordID": "790359",
   "Boro": "STATEN ISLAND",
   "HouseNumber": "411",
   "LowHouseNumber": "411",
   "HighHouseNumber": "411",
   "StreetName": "VANDERBILT AVENUE",
   "StreetCode": "52850",
   "Zip": "10304",
   "FIELD10": "411 VANDERBILT AVENUE New York, NY 10304",
   "Apartment": "25",
   "Story": "",
   "num": "177",
   "a": "24",
   "b": "130",
   "c": "21",
   "i": "2",
   "dob": "1",
   "BIN": "5016362",
   "dob_hpd": "178",
   "score": "9.61765",
   "A_UNITS": "17",
   "B_UNITS": "0",
   "OWNER1": "DELAWARE ARMS INC",
   "ORGANIZATION": "DELAWARE ARMS INC",
   "OWNER1_LN": "JENNINGS",
   "OWNER1_FN": "RALPH ",
   "officer": "RALPH  JENNINGS",
   "org": "DELAWARE ARMS INC",
   "lat": "40.61589432",
   "lng": "-74.08410645",
   "exclude": "0",
   "worstLandlord": null,
   "UNITS": "17",
   "DOF": "0"
 },
 {
   "BuildingID": "793709",
   "LandlordID": null,
   "Boro": "STATEN ISLAND",
   "HouseNumber": "410",
   "LowHouseNumber": "410",
   "HighHouseNumber": "410",
   "StreetName": "WESTERVELT AVENUE",
   "StreetCode": "54950",
   "Zip": "10301",
   "FIELD10": "410 WESTERVELT AVENUE New York, NY 10301",
   "Apartment": "2",
   "Story": "",
   "num": "140",
   "a": "14",
   "b": "92",
   "c": "33",
   "i": "1",
   "dob": "0",
   "BIN": "5000752",
   "dob_hpd": "140",
   "score": "47.1667",
   "A_UNITS": "3",
   "B_UNITS": "0",
   "OWNER1": null,
   "ORGANIZATION": null,
   "OWNER1_LN": "ARDOLIC",
   "OWNER1_FN": "ZUHRA ",
   "officer": "ZUHRA  ARDOLIC",
   "org": null,
   "lat": "40.63819504",
   "lng": "-74.08208466",
   "exclude": "0",
   "worstLandlord": null,
   "UNITS": "3",
   "DOF": "0"
 },
 {
   "BuildingID": "746071",
   "LandlordID": "746071",
   "Boro": "STATEN ISLAND",
   "HouseNumber": "60",
   "LowHouseNumber": "60",
   "HighHouseNumber": "60",
   "StreetName": "HOLLAND AVENUE",
   "StreetCode": "33200",
   "Zip": "10303",
   "FIELD10": "60 HOLLAND AVENUE New York, NY 10303",
   "Apartment": "",
   "Story": "Cellar",
   "num": "130",
   "a": "16",
   "b": "81",
   "c": "33",
   "i": "0",
   "dob": "0",
   "BIN": "5028645",
   "dob_hpd": "130",
   "score": "32.625",
   "A_UNITS": "4",
   "B_UNITS": "0",
   "OWNER1": "ARTHUR KILL PROPERTIES INC",
   "ORGANIZATION": "ARTHUR KILL PROPERTIES INC",
   "OWNER1_LN": "SARDINA",
   "OWNER1_FN": "FRANK T",
   "officer": "FRANK T SARDINA",
   "org": "ARTHUR KILL PROPERTIES INC",
   "lat": "40.63883209",
   "lng": "-74.17155457",
   "exclude": "0",
   "worstLandlord": null,
   "UNITS": "4",
   "DOF": "2"
 },
 {
   "BuildingID": "791834",
   "LandlordID": "791834",
   "Boro": "STATEN ISLAND",
   "HouseNumber": "90",
   "LowHouseNumber": "90",
   "HighHouseNumber": "90",
   "StreetName": "VREELAND STREET",
   "StreetCode": "53600",
   "Zip": "10302",
   "FIELD10": "90 VREELAND STREET New York, NY 10302",
   "Apartment": "",
   "Story": "1",
   "num": "84",
   "a": "11",
   "b": "68",
   "c": "5",
   "i": "0",
   "dob": "3",
   "BIN": "5023991",
   "dob_hpd": "87",
   "score": "5.09375",
   "A_UNITS": "3",
   "B_UNITS": "13",
   "OWNER1": "FIRST STREET REALTY, LLC",
   "ORGANIZATION": "FIRST STREET REALTY, LLC",
   "OWNER1_LN": "PARKER",
   "OWNER1_FN": "KENNETH ",
   "officer": "KENNETH  PARKER",
   "org": "FIRST STREET REALTY, LLC",
   "lat": "40.63713837",
   "lng": "-74.13313293",
   "exclude": "0",
   "worstLandlord": null,
   "UNITS": "16",
   "DOF": "0"
 },
 {
   "BuildingID": "717681",
   "LandlordID": "717681",
   "Boro": "STATEN ISLAND",
   "HouseNumber": "44",
   "LowHouseNumber": "44",
   "HighHouseNumber": "44",
   "StreetName": "BRIGHTON AVENUE",
   "StreetCode": "19850",
   "Zip": "10301",
   "FIELD10": "44 BRIGHTON AVENUE New York, NY 10301",
   "Apartment": "",
   "Story": "",
   "num": "74",
   "a": "10",
   "b": "57",
   "c": "5",
   "i": "2",
   "dob": "3",
   "BIN": "5002497",
   "dob_hpd": "77",
   "score": "23.5",
   "A_UNITS": "3",
   "B_UNITS": "0",
   "OWNER1": "JWL ENTERPRISES",
   "ORGANIZATION": "JWL ENTERPRISES",
   "OWNER1_LN": "LAFORTE",
   "OWNER1_FN": "JOSEPH ",
   "officer": "JOSEPH  LAFORTE",
   "org": "JWL ENTERPRISES",
   "lat": "40.63711548",
   "lng": "-74.08822632",
   "exclude": "0",
   "worstLandlord": null,
   "UNITS": "3",
   "DOF": "0"
 },
 {
   "BuildingID": "794394",
   "LandlordID": "794394",
   "Boro": "STATEN ISLAND",
   "HouseNumber": "51",
   "LowHouseNumber": "51",
   "HighHouseNumber": "51",
   "StreetName": "WILBUR STREET",
   "StreetCode": "55400",
   "Zip": "10309",
   "FIELD10": "51 WILBUR STREET New York, NY 10309",
   "Apartment": "",
   "Story": "Cellar",
   "num": "68",
   "a": "8",
   "b": "53",
   "c": "7",
   "i": "0",
   "dob": "6",
   "BIN": "5082754",
   "dob_hpd": "74",
   "score": "3.28261",
   "A_UNITS": "1",
   "B_UNITS": "22",
   "OWNER1": "GUDDEMI PROPERTIES INC",
   "ORGANIZATION": "GUDDEMI PROPERTIES INC",
   "OWNER1_LN": "GUDDEMI",
   "OWNER1_FN": "ANTHONY ",
   "officer": "ANTHONY  GUDDEMI",
   "org": "GUDDEMI PROPERTIES INC",
   "lat": "40.51553726",
   "lng": "-74.19469452",
   "exclude": "0",
   "worstLandlord": null,
   "UNITS": "23",
   "DOF": "0"
 },
 {
   "BuildingID": "782970",
   "LandlordID": "782970",
   "Boro": "STATEN ISLAND",
   "HouseNumber": "1",
   "LowHouseNumber": "1",
   "HighHouseNumber": "3",
   "StreetName": "SLOSSON TERRACE",
   "StreetCode": "48200",
   "Zip": "10301",
   "FIELD10": "1 SLOSSON TERRACE New York, NY 10301",
   "Apartment": "",
   "Story": "",
   "num": "69",
   "a": "11",
   "b": "57",
   "c": "1",
   "i": "0",
   "dob": "1",
   "BIN": "5000039",
   "dob_hpd": "70",
   "score": "4.03333",
   "A_UNITS": "1",
   "B_UNITS": "14",
   "OWNER1": "1-3 SLOSSON TERRACE, INC",
   "ORGANIZATION": "1-3 SLOSSON TERRACE, INC",
   "OWNER1_LN": "PATEL",
   "OWNER1_FN": "SAVITABEN K",
   "officer": "SAVITABEN K PATEL",
   "org": "1-3 SLOSSON TERRACE, INC",
   "lat": "40.63982773",
   "lng": "-74.07575226",
   "exclude": "0",
   "worstLandlord": null,
   "UNITS": "15",
   "DOF": "0"
 },
 {
   "BuildingID": "717977",
   "LandlordID": "717977",
   "Boro": "STATEN ISLAND",
   "HouseNumber": "209",
   "LowHouseNumber": "209",
   "HighHouseNumber": "209",
   "StreetName": "BROAD STREET",
   "StreetCode": "20300",
   "Zip": "10304",
   "FIELD10": "209 BROAD STREET New York, NY 10304",
   "Apartment": "",
   "Story": "",
   "num": "65",
   "a": "25",
   "b": "35",
   "c": "5",
   "i": "0",
   "dob": "3",
   "BIN": "5014053",
   "dob_hpd": "68",
   "score": "12.125",
   "A_UNITS": "4",
   "B_UNITS": "0",
   "OWNER1": "J&M BROAD PROPERTY LLC",
   "ORGANIZATION": "J&M BROAD PROPERTY LLC",
   "OWNER1_LN": "ALI",
   "OWNER1_FN": "JAMAL M",
   "officer": "JAMAL M ALI",
   "org": "J&M BROAD PROPERTY LLC",
   "lat": "40.62414551",
   "lng": "-74.08184052",
   "exclude": "0",
   "worstLandlord": null,
   "UNITS": "4",
   "DOF": "0"
 },
 {
   "BuildingID": "789648",
   "LandlordID": "717681",
   "Boro": "STATEN ISLAND",
   "HouseNumber": "1042",
   "LowHouseNumber": "1042",
   "HighHouseNumber": "1042",
   "StreetName": "VAN DUZER STREET",
   "StreetCode": "52550",
   "Zip": "10304",
   "FIELD10": "1042 VAN DUZER STREET New York, NY 10304",
   "Apartment": "",
   "Story": "",
   "num": "68",
   "a": "9",
   "b": "48",
   "c": "8",
   "i": "3",
   "dob": "0",
   "BIN": "5016054",
   "dob_hpd": "68",
   "score": "20",
   "A_UNITS": "3",
   "B_UNITS": "0",
   "OWNER1": null,
   "ORGANIZATION": null,
   "OWNER1_LN": "LAFORTE",
   "OWNER1_FN": "JOSEPH ",
   "officer": "JOSEPH  LAFORTE",
   "org": null,
   "lat": "40.61369324",
   "lng": "-74.08763885",
   "exclude": "0",
   "worstLandlord": null,
   "UNITS": "3",
   "DOF": "0"
 },
 {
   "BuildingID": "749665",
   "LandlordID": null,
   "Boro": "STATEN ISLAND",
   "HouseNumber": "264",
   "LowHouseNumber": "264",
   "HighHouseNumber": "264",
   "StreetName": "JEWETT AVENUE",
   "StreetCode": "34850",
   "Zip": "10302",
   "FIELD10": "264 JEWETT AVENUE New York, NY 10302",
   "Apartment": "1F",
   "Story": "1",
   "num": "64",
   "a": "21",
   "b": "36",
   "c": "6",
   "i": "1",
   "dob": "0",
   "BIN": "5024355",
   "dob_hpd": "64",
   "score": "11.25",
   "A_UNITS": "4",
   "B_UNITS": "0",
   "OWNER1": null,
   "ORGANIZATION": null,
   "OWNER1_LN": "YOUBOTY",
   "OWNER1_FN": "EVA ",
   "officer": "EVA  YOUBOTY",
   "org": null,
   "lat": "40.63059616",
   "lng": "-74.13067627",
   "exclude": "0",
   "worstLandlord": null,
   "UNITS": "4",
   "DOF": "0"
 },
 {
   "BuildingID": "717679",
   "LandlordID": null,
   "Boro": "STATEN ISLAND",
   "HouseNumber": "42",
   "LowHouseNumber": "42",
   "HighHouseNumber": "42",
   "StreetName": "BRIGHTON AVENUE",
   "StreetCode": "19850",
   "Zip": "10301",
   "FIELD10": "42 BRIGHTON AVENUE New York, NY 10301",
   "Apartment": "3FL",
   "Story": "3",
   "num": "58",
   "a": "20",
   "b": "26",
   "c": "10",
   "i": "2",
   "dob": "4",
   "BIN": "5002498",
   "dob_hpd": "62",
   "score": "16.3333",
   "A_UNITS": "3",
   "B_UNITS": "0",
   "OWNER1": null,
   "ORGANIZATION": null,
   "OWNER1_LN": "DOLAN",
   "OWNER1_FN": "JOHN ",
   "officer": "NULL",
   "org": null,
   "lat": "40.637172",
   "lng": "-74.088195",
   "exclude": "0",
   "worstLandlord": null,
   "UNITS": "3",
   "DOF": "0"
 },
 {
   "BuildingID": "776577",
   "LandlordID": "776577",
   "Boro": "STATEN ISLAND",
   "HouseNumber": "1918",
   "LowHouseNumber": "1918",
   "HighHouseNumber": "1918",
   "StreetName": "RICHMOND TERRACE",
   "StreetCode": "45050",
   "Zip": "10302",
   "FIELD10": "1918 RICHMOND TERRACE New York, NY 10302",
   "Apartment": "",
   "Story": "2",
   "num": "62",
   "a": "17",
   "b": "32",
   "c": "13",
   "i": "0",
   "dob": "0",
   "BIN": "5023776",
   "dob_hpd": "62",
   "score": "12.875",
   "A_UNITS": "4",
   "B_UNITS": "0",
   "OWNER1": "27 EAGLE LLC",
   "ORGANIZATION": "27 EAGLE LLC",
   "OWNER1_LN": "MIN",
   "OWNER1_FN": "CARL K",
   "officer": "CARL K MIN",
   "org": "27 EAGLE LLC",
   "lat": "40.63758469",
   "lng": "-74.12901306",
   "exclude": "0",
   "worstLandlord": null,
   "UNITS": "4",
   "DOF": "0"
 },
 {
   "BuildingID": "790373",
   "LandlordID": "790373",
   "Boro": "STATEN ISLAND",
   "HouseNumber": "487",
   "LowHouseNumber": "487",
   "HighHouseNumber": "489",
   "StreetName": "VANDERBILT AVENUE",
   "StreetCode": "52850",
   "Zip": "10304",
   "FIELD10": "487 VANDERBILT AVENUE New York, NY 10304",
   "Apartment": "",
   "Story": "Cellar",
   "num": "61",
   "a": "13",
   "b": "31",
   "c": "16",
   "i": "1",
   "dob": "0",
   "BIN": "5016476",
   "dob_hpd": "61",
   "score": "18.3333",
   "A_UNITS": "3",
   "B_UNITS": "0",
   "OWNER1": "TARAVAN HOLDING LLC",
   "ORGANIZATION": "TARAVAN HOLDING LLC",
   "OWNER1_LN": "MOFTAH",
   "OWNER1_FN": "NED ",
   "officer": "NED  MOFTAH",
   "org": "TARAVAN HOLDING LLC",
   "lat": "40.61458588",
   "lng": "-74.08583832",
   "exclude": "0",
   "worstLandlord": null,
   "UNITS": "3",
   "DOF": "0"
 },
 {
   "BuildingID": "718042",
   "LandlordID": "718042",
   "Boro": "STATEN ISLAND",
   "HouseNumber": "91",
   "LowHouseNumber": "91",
   "HighHouseNumber": "91",
   "StreetName": "BROAD STREET",
   "StreetCode": "20300",
   "Zip": "10304",
   "FIELD10": "91 BROAD STREET New York, NY 10304",
   "Apartment": "",
   "Story": "1",
   "num": "56",
   "a": "18",
   "b": "26",
   "c": "12",
   "i": "0",
   "dob": "0",
   "BIN": "5013778",
   "dob_hpd": "56",
   "score": "7.33333",
   "A_UNITS": "6",
   "B_UNITS": "0",
   "OWNER1": "91 BROAD STREET REALTY LLC",
   "ORGANIZATION": "91 BROAD STREET REALTY LLC",
   "OWNER1_LN": "BARRETTI",
   "OWNER1_FN": "PHILIP ",
   "officer": "PHILIP  BARRETTI",
   "org": "91 BROAD STREET REALTY LLC",
   "lat": "40.625213",
   "lng": "-74.078491",
   "exclude": "0",
   "worstLandlord": null,
   "UNITS": "6",
   "DOF": "2"
 },
 {
   "BuildingID": "753984",
   "LandlordID": "753984",
   "Boro": "STATEN ISLAND",
   "HouseNumber": "28",
   "LowHouseNumber": "28",
   "HighHouseNumber": "28",
   "StreetName": "LAYTON AVENUE",
   "StreetCode": "36050",
   "Zip": "10301",
   "FIELD10": "28 LAYTON AVENUE New York, NY 10301",
   "Apartment": "3",
   "Story": "3",
   "num": "54",
   "a": "8",
   "b": "40",
   "c": "4",
   "i": "2",
   "dob": "0",
   "BIN": "5000899",
   "dob_hpd": "54",
   "score": "15.3333",
   "A_UNITS": "3",
   "B_UNITS": "0",
   "OWNER1": "DOMINICK GRASSO",
   "ORGANIZATION": "DOMINICK GRASSO",
   "OWNER1_LN": "STROMFELD",
   "OWNER1_FN": "ALAN ",
   "officer": "ALAN  STROMFELD",
   "org": "NULL",
   "lat": "40.64150238",
   "lng": "-74.08421326",
   "exclude": "0",
   "worstLandlord": null,
   "UNITS": "3",
   "DOF": "0"
 },
 {
   "BuildingID": "721771",
   "LandlordID": null,
   "Boro": "STATEN ISLAND",
   "HouseNumber": "145",
   "LowHouseNumber": "145",
   "HighHouseNumber": "145",
   "StreetName": "CEDAR AVENUE",
   "StreetCode": "22250",
   "Zip": "10305",
   "FIELD10": "145 CEDAR AVENUE New York, NY 10305",
   "Apartment": "",
   "Story": "Cellar",
   "num": "52",
   "a": "15",
   "b": "29",
   "c": "6",
   "i": "2",
   "dob": "1",
   "BIN": "5045777",
   "dob_hpd": "53",
   "score": "8",
   "A_UNITS": "5",
   "B_UNITS": "0",
   "OWNER1": null,
   "ORGANIZATION": null,
   "OWNER1_LN": "RODRIGUEZ",
   "OWNER1_FN": "MARIA ",
   "officer": "MARIA  RODRIGUEZ",
   "org": null,
   "lat": "40.59637451",
   "lng": "-74.06750488",
   "exclude": "0",
   "worstLandlord": null,
   "UNITS": "5",
   "DOF": "0"
 },
 {
   "BuildingID": "797817",
   "LandlordID": "797817",
   "Boro": "STATEN ISLAND",
   "HouseNumber": "238",
   "LowHouseNumber": "236",
   "HighHouseNumber": "238",
   "StreetName": "YORK AVENUE",
   "StreetCode": "56600",
   "Zip": "10301",
   "FIELD10": "238 YORK AVENUE New York, NY 10301",
   "Apartment": "",
   "Story": "All Stories",
   "num": "53",
   "a": "2",
   "b": "43",
   "c": "6",
   "i": "2",
   "dob": "0",
   "BIN": "5001253",
   "dob_hpd": "53",
   "score": "13",
   "A_UNITS": "4",
   "B_UNITS": "0",
   "OWNER1": "YORK PROSPECT CORNER LLC",
   "ORGANIZATION": "YORK PROSPECT CORNER LLC",
   "OWNER1_LN": "ASSKR",
   "OWNER1_FN": "MOHAMMED A",
   "officer": "MOHAMMED A ASSKR",
   "org": "YORK PROSPECT CORNER LLC",
   "lat": "40.64044189",
   "lng": "-74.08818054",
   "exclude": "0",
   "worstLandlord": null,
   "UNITS": "4",
   "DOF": "0"
 },
 {
   "BuildingID": "812541",
   "LandlordID": "812541",
   "Boro": "STATEN ISLAND",
   "HouseNumber": "55",
   "LowHouseNumber": "55",
   "HighHouseNumber": "55",
   "StreetName": "RACAL COURT",
   "StreetCode": "44530",
   "Zip": "10314",
   "FIELD10": "55 RACAL COURT New York, NY 10314",
   "Apartment": "3",
   "Story": "3",
   "num": "52",
   "a": "6",
   "b": "43",
   "c": "3",
   "i": "0",
   "dob": "0",
   "BIN": "5039675",
   "dob_hpd": "52",
   "score": "15.8333",
   "A_UNITS": "3",
   "B_UNITS": "0",
   "OWNER1": "ELJ PARIS LLC",
   "ORGANIZATION": "ELJ PARIS LLC",
   "OWNER1_LN": "PARASCANDO",
   "OWNER1_FN": "LOUIS ",
   "officer": "LOUIS  PARASCANDO",
   "org": "ELJ PARIS LLC",
   "lat": "40.586074",
   "lng": "-74.164665",
   "exclude": "0",
   "worstLandlord": null,
   "UNITS": "3",
   "DOF": "0"
 },
 {
   "BuildingID": "789070",
   "LandlordID": "717681",
   "Boro": "STATEN ISLAND",
   "HouseNumber": "61",
   "LowHouseNumber": "61",
   "HighHouseNumber": "61",
   "StreetName": "TYSEN STREET",
   "StreetCode": "52100",
   "Zip": "10301",
   "FIELD10": "61 TYSEN STREET New York, NY 10301",
   "Apartment": "",
   "Story": "All Stories",
   "num": "50",
   "a": "5",
   "b": "33",
   "c": "10",
   "i": "2",
   "dob": "0",
   "BIN": "5001741",
   "dob_hpd": "50",
   "score": "16",
   "A_UNITS": "3",
   "B_UNITS": "0",
   "OWNER1": null,
   "ORGANIZATION": null,
   "OWNER1_LN": "LAFORTE",
   "OWNER1_FN": "JOSEPH ",
   "officer": "JOSEPH  LAFORTE",
   "org": null,
   "lat": "40.64410782",
   "lng": "-74.0993042",
   "exclude": "0",
   "worstLandlord": null,
   "UNITS": "3",
   "DOF": "1"
 }
];
	
	var lng = "";
	var count = "";
	var pins = "";
		
		
	
var hotel = "";
var Rank = "";
var buildings = "";
var aunits = "";
var bunits = "";
var units = "";
var hpd = "";
var dob = "";
var hc = "";
var name = "";
var map = "";
var cajahotelHTML = "";
var hotelContainerHTML = "";
	var lng = "";
	var count = "";
	var pins = "";
		
		
	
var hotel = "";
var Rank = "";
var buildings = "";
var aunits = "";
var bunits = "";
var units = "";
var hpd = "";
var dob = "";
var hc = "";
var name = "";
var map = "";
var cajahotelHTML = "";
var cajahotelHTML2 = "";
var cajahotelHTML3 = "";
var addstring = "";
var hotelContainerHTML = "";
var org = "";
		var replaced = "";




 				

    for (var j = 0; j < markers.length; j++){
	var data=markers[j];
if (markers[j].DOF > 0)
		{
			var DOF2 = "Yes";
		}
		else{
			DOF2= "No";
		}
		var box = "";
		replaced = markers[j].StreetName.split(' ').join('+');
		var lat = "";
		address = '<headll>' + markers[j].HouseNumber + ' ' + markers[j].StreetName + ', ' + markers[j].Boro + ' ' + markers[j].Zip + '</headll>';
		org = '<div class="pnum">Organization: ' + markers[j].org + '</div>';
		Rank = '<div class="pnum">Landlord Rank <g>' + markers[j].Rank + '</g></div>';
		var	Rank2 = '<headll>' + markers[j].Rank + '. </headll>';
		addstring = '' + markers[j].HouseNumber + '+' + replaced + ',+' + markers[j].Boro + ',+' + markers[j].Zip + ''
		buildings = '<pnum>Number of Buildings ' + markers[j].buildings + '</pnum>';
		hpd = '<div class="pnum">Number of HPD Violations <d>' + markers[j].num + '</d></div>';
		dob = '<div class="pnum">Number of DOB Violations <d>' + markers[j].dob + '</d></div>';
		hc = '<div class="pnum">Number of Housing Court Actions <d>' + markers[j].housingCourt + '</d></div>';
		name = '' + markers[j].officer + '';
				var name2 = '<div class="pnum">Landlord: ' + markers[j].officer + '</div>';
	dof = '<div class="pnum">Tax lien sold in last two years : <d>' + DOF2 + '</d></div>';
		map = '<div id="' + markers[j].DIVH + '" style="top: 10px; left: 25px; width:100%; height:85%; float: left"></div>';
		lat = '' + markers[j].lat + ',' + markers[j].lng + '';
			
	
	
		var url = 'https://maps.googleapis.com/maps/api/streetview?size=600x400&location=' + addstring + '%20&fov=90&pitch=0%20&key=AIzaSyCEdL7GSizXOkrhG1vJWSRro4wlyqo5kdU';
		 box += '<div class="col-md-13"><div class="col-md-12-head"><headll>' + address + '</headll></div><div class="col-md-2"> <a href="map.html"><img class="img-responsive" alt="landlordmap" src="si/si' + (j+1) + '.jpeg"></a></div><div class="col-md-3"><div class="buildingRates"></span><span>' + name2 + '</span><span>' + org + '</span><span>' + units + '</span><span>' + hpd + '</span><span>' + dob + '</span><span>' + dof + '</span></div></div></div>';
			
		
	
	
	cajahotelHTML =   box  ;
	

  hotelContainerHTML += cajahotelHTML;
}

var outputDiv = document.getElementById('scrollDiv');
outputDiv.innerHTML = hotelContainerHTML;







